name: Docker
on: [workflow_dispatch]

jobs:
    docker-job:
        runs-on: ubuntu-latest
        container:  
            image: node:20.3-alpine3.17
    #         credentials:
    #            username: ${{ secrets.DOCKER_USERNAME }}
    #            password: ${{ secrets.DOCKER_PASSWORD }}
            env:
                API_URL: some-url.com
            ports:
                - 80
         #   volumes:
         #       - /var/run/docker.sock:/var/run/docker.sock
         #       - path/to/container
         #       - path/in/host: /path/in/container
         #    options: --cpus 1 --memory 1G
        steps:
            - name: Log node & OS version
              run: |
                 echo "Node version: $(node -v)"
                 cat /etc/os-realease
        
            - name: Log env
              run: echo $API_URL
   