name: Environment Variables

on: [push]
env:
    WF_LEVEL_ENV: Available to all jobs

jobs: 
    env-vars-and-context:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        env:
            JOB_LEVEL_ENV: Available to this job
        steps:
            - name: Log env Var
              run: echo $GITHUB_REF
            - name: Log context
              run: echo '${{ github.ref }}'
            - name: Setting env var
              run: |
               echo "NEW_ENV_VAR=$(date)" >> $GITHUB_ENV
               echo "JOB_LEVEL_ENV=$RANDOM" >> "$GITHUB_ENV"
            - name: Multiline Env VAr
              run: |
                DELIMITER=';'
                echo "RANDOM_JOKE << $DELIMITER" >> "$GITHUB_ENV"
            
                echo "yOU ARE AN IDIOT  ja ja ja ja ja ja ja " >> "$GITHUB_ENV"
                curl -s https://icanhazdadjoke.com/ >> "$GITHUB_ENV"
                echo "" >> "$GITHUB_ENV"
                echo "$DELIMITER" >> "$GITHUB_ENV"
            - name: Log Custom Env Vars
              env:
                STEP_LEVEL_ENV: Available to this step
                WF_LEVEL_ENV: oVERRIDEN IN STEP
              run: |
                    echo '${{env.STEP_LEVEL_ENV}}'
                    echo $STEP_LEVEL_ENV
                    echo $WF_LEVEL_ENV
                    echo $JOB_LEVEL_ENV
                    echo $NEW_ENV_VAR